version: '3'

services:
  workspace:
    build: docker/workspace
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=foo
      - MYSQL_PASSWORD=bar
      - MYSQL_DATABASE=shortener
  
  nginx:
    image: nginx
    ports:
      - "8081:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    depends_on:
      - workspace

  worker:
    build: docker/workspace
    command: php artisan queue:work redis
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application

  redis:
    image: redis
    ports:
      - "6379:6379"
